"""delete and recreate

Revision ID: 6fd5051b88be
Revises: 
Create Date: 2023-03-12 20:08:30.791079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd5051b88be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_primary', sa.String(), nullable=True),
    sa.Column('phone_secondary', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credits', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_primary'),
    sa.UniqueConstraint('phone_secondary'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('km_driven', sa.Integer(), nullable=False),
    sa.Column('no_of_owners', sa.SmallInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('main_pic', sa.String(), nullable=False),
    sa.Column('pic0', sa.String(), nullable=True),
    sa.Column('pic1', sa.String(), nullable=True),
    sa.Column('pic2', sa.String(), nullable=True),
    sa.Column('pic3', sa.String(), nullable=True),
    sa.Column('pic4', sa.String(), nullable=True),
    sa.Column('pic5', sa.String(), nullable=True),
    sa.Column('pic6', sa.String(), nullable=True),
    sa.Column('pic7', sa.String(), nullable=True),
    sa.Column('pic8', sa.String(), nullable=True),
    sa.Column('pic9', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
